### ISSUE TITLE
Add new and different insights to the paper

### ISSUE THREAD

**Issue by jwbowers** [jwbowers/workflow#3]
I recall that Maarten had great thoughts about directory stuctures, file names, and other approaches to organizing work.

**Comment by maartenvoors** [comment]
Great thoughts any day!  What is our time window on this paper?

**Comment by jwbowers** [comment]
I think that Fernando would like something in the next couple of weeks. Maybe you can add to/change the paper given your great thoughts in the next week? And then I can give it one more look before sending to him and Thad?

**Comment by maartenvoors** [comment]
great, will try to get to it this week!
